# Generated by Django 3.0.2 on 2020-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0004_auto_20200110_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
