# Generated by Django 3.0.2 on 2020-01-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0005_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
